// products.js

export const products = [
  {
    product_id: 1,
    licence_name: "Pokemon",
    category_name: "Figuras coleccionables",
    product_name: "Pidgeotto",
    product_description: "Figura coleccionable pokemon",
    product_price: 1799.99,
    dues: 10,
    product_sku: "PKM001001",
    img_front: "/img/pokemon/pidgeotto-1.webp",
    img_back: "/img/pokemon/pidgeotto-box.webp",
  },
  {
    product_id: 2,
    licence_name: "STAR WARS",
    category_name: "Figuras coleccionables",
    product_name: "STORMTROOPER LIGHTSABER",
    product_description: "Figura coleccionable Star Wars",
    product_price: 1799.99,
    dues: 3,
    product_sku: "SW001001",
    img_front: "/img/star-wars/trooper-1.webp",
    img_back: "/img/star-wars/trooper-box.webp",
  },
  {
    product_id: 3,
    licence_name: "HARRY POTTER",
    category_name: "Figuras coleccionables",
    product_name: "MUÑECO HARRY POTTER",
    product_description: "Descripcion Harry Potter",
    product_price: 1992.99,
    dues: 6,
    product_sku: "SW001002",
    img_front: "/img/harry-potter/harry-1.webp",
    img_back: "/img/harry-potter/harry-box.webp",
  },
  {
    product_id: 4,
    licence_name: "Luna",
    category_name: "Figuras coleccionables",
    product_name: "MUÑECO LUNA",
    product_description: "Descripcion LUNA",
    product_price: 1522.99,
    dues: 9,
    product_sku: "SW001002",
    img_front: "/img/harry-potter/luna-1.webp",
    img_back: "/img/harry-potter/luna-box.webp",
  },
];
